python/cmap/io/gct.py: fix unicode2str function
This was broken in Python 2, in addition to the `unicode` type no longer
existing in Python 3. (There are only `str`: sequences of Unicode code points,
and `bytes`: sequences of integers in the range [0, 255]).

The unicode2str function failed in most (all?) installations of Python 2:

"""
>>> unicode2str = lambda x: str(x) if type(x) is unicode else x
>>> unicode2str(u'TGFβ1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b2' in position 3: ordinal not in range(128)
>>> # That threw an exception, because of this:
...
 >>> import sys; sys.getdefaultencoding()
'ascii'
"""

It seems appropriate to handle all Unicode code points by explicitly encoding
to UTF-8, instead of using the system default encoding via the call to str(x).